// <auto-generated />
using System;
using Acmp.Modules.Actions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acmp.Modules.Actions.Infrastructure.Migrations
{
    [DbContext(typeof(ActionsDbContext))]
    [Migration("20260701052304_Actions_Init")]
    partial class Actions_Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("actions")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acmp.Modules.Actions.Domain.ActionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CompletedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("MeetingKey")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProgressPct")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VerifiedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VerifiedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("SourceType", "SourceId");

                    b.ToTable("actions", "actions");
                });

            modelBuilder.Entity("Acmp.Modules.Actions.Infrastructure.Persistence.ActionKeyCounter", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Next")
                        .HasColumnType("int");

                    b.HasKey("Prefix", "Year");

                    b.ToTable("action_key_counters", "actions");
                });

            modelBuilder.Entity("Acmp.Modules.Actions.Domain.ActionItem", b =>
                {
                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "BlockedReason", b1 =>
                        {
                            b1.Property<long>("ActionItemId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("blocked_reason_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("blocked_reason_en");

                            b1.HasKey("ActionItemId");

                            b1.ToTable("actions", "actions");

                            b1.WithOwner()
                                .HasForeignKey("ActionItemId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "CancelReason", b1 =>
                        {
                            b1.Property<long>("ActionItemId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("cancel_reason_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("cancel_reason_en");

                            b1.HasKey("ActionItemId");

                            b1.ToTable("actions", "actions");

                            b1.WithOwner()
                                .HasForeignKey("ActionItemId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "CompletionNote", b1 =>
                        {
                            b1.Property<long>("ActionItemId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("completion_note_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("completion_note_en");

                            b1.HasKey("ActionItemId");

                            b1.ToTable("actions", "actions");

                            b1.WithOwner()
                                .HasForeignKey("ActionItemId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Description", b1 =>
                        {
                            b1.Property<long>("ActionItemId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("description_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("description_en");

                            b1.HasKey("ActionItemId");

                            b1.ToTable("actions", "actions");

                            b1.WithOwner()
                                .HasForeignKey("ActionItemId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Title", b1 =>
                        {
                            b1.Property<long>("ActionItemId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("title_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("title_en");

                            b1.HasKey("ActionItemId");

                            b1.ToTable("actions", "actions");

                            b1.WithOwner()
                                .HasForeignKey("ActionItemId");
                        });

                    b.Navigation("BlockedReason");

                    b.Navigation("CancelReason");

                    b.Navigation("CompletionNote");

                    b.Navigation("Description");

                    b.Navigation("Title")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
