// <auto-generated />
using System;
using Acmp.Modules.Governance.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acmp.Modules.Governance.Infrastructure.Migrations
{
    [DbContext(typeof(GovernanceDbContext))]
    partial class GovernanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("governance")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acmp.Modules.Governance.Domain.Adr", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ApprovedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ApprovedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AuthorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SourceDecisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupersededByAdrId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersedesAdrId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("adrs", "governance");
                });

            modelBuilder.Entity("Acmp.Modules.Governance.Infrastructure.Persistence.AdrKeyCounter", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Next")
                        .HasColumnType("int");

                    b.HasKey("Prefix", "Year");

                    b.ToTable("adr_key_counters", "governance");
                });

            modelBuilder.Entity("Acmp.Modules.Governance.Domain.Adr", b =>
                {
                    b.OwnsMany("Acmp.Modules.Governance.Domain.AdrOption", "Options", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<long>("AdrEntityId")
                                .HasColumnType("bigint");

                            b1.Property<bool>("IsChosen")
                                .HasColumnType("bit");

                            b1.Property<Guid>("PublicId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("AdrEntityId");

                            b1.HasIndex("PublicId")
                                .IsUnique();

                            b1.ToTable("adr_options", "governance");

                            b1.WithOwner()
                                .HasForeignKey("AdrEntityId");

                            b1.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Body", b2 =>
                                {
                                    b2.Property<long>("AdrOptionId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Ar")
                                        .IsRequired()
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("body_ar");

                                    b2.Property<string>("En")
                                        .IsRequired()
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("body_en");

                                    b2.HasKey("AdrOptionId");

                                    b2.ToTable("adr_options", "governance");

                                    b2.WithOwner()
                                        .HasForeignKey("AdrOptionId");
                                });

                            b1.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Name", b2 =>
                                {
                                    b2.Property<long>("AdrOptionId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Ar")
                                        .IsRequired()
                                        .HasMaxLength(512)
                                        .HasColumnType("nvarchar(512)")
                                        .HasColumnName("name_ar");

                                    b2.Property<string>("En")
                                        .IsRequired()
                                        .HasMaxLength(512)
                                        .HasColumnType("nvarchar(512)")
                                        .HasColumnName("name_en");

                                    b2.HasKey("AdrOptionId");

                                    b2.ToTable("adr_options", "governance");

                                    b2.WithOwner()
                                        .HasForeignKey("AdrOptionId");
                                });

                            b1.Navigation("Body");

                            b1.Navigation("Name")
                                .IsRequired();
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "ConsequencesNegative", b1 =>
                        {
                            b1.Property<long>("AdrId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("consequences_negative_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("consequences_negative_en");

                            b1.HasKey("AdrId");

                            b1.ToTable("adrs", "governance");

                            b1.WithOwner()
                                .HasForeignKey("AdrId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "ConsequencesPositive", b1 =>
                        {
                            b1.Property<long>("AdrId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("consequences_positive_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("consequences_positive_en");

                            b1.HasKey("AdrId");

                            b1.ToTable("adrs", "governance");

                            b1.WithOwner()
                                .HasForeignKey("AdrId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Context", b1 =>
                        {
                            b1.Property<long>("AdrId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("context_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("context_en");

                            b1.HasKey("AdrId");

                            b1.ToTable("adrs", "governance");

                            b1.WithOwner()
                                .HasForeignKey("AdrId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "DecisionDrivers", b1 =>
                        {
                            b1.Property<long>("AdrId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("decision_drivers_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("decision_drivers_en");

                            b1.HasKey("AdrId");

                            b1.ToTable("adrs", "governance");

                            b1.WithOwner()
                                .HasForeignKey("AdrId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "DecisionText", b1 =>
                        {
                            b1.Property<long>("AdrId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("decision_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("decision_en");

                            b1.HasKey("AdrId");

                            b1.ToTable("adrs", "governance");

                            b1.WithOwner()
                                .HasForeignKey("AdrId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "DeprecationReason", b1 =>
                        {
                            b1.Property<long>("AdrId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("deprecation_reason_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("deprecation_reason_en");

                            b1.HasKey("AdrId");

                            b1.ToTable("adrs", "governance");

                            b1.WithOwner()
                                .HasForeignKey("AdrId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "SupersessionReason", b1 =>
                        {
                            b1.Property<long>("AdrId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("supersession_reason_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("supersession_reason_en");

                            b1.HasKey("AdrId");

                            b1.ToTable("adrs", "governance");

                            b1.WithOwner()
                                .HasForeignKey("AdrId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Title", b1 =>
                        {
                            b1.Property<long>("AdrId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("title_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("title_en");

                            b1.HasKey("AdrId");

                            b1.ToTable("adrs", "governance");

                            b1.WithOwner()
                                .HasForeignKey("AdrId");
                        });

                    b.Navigation("ConsequencesNegative");

                    b.Navigation("ConsequencesPositive");

                    b.Navigation("Context")
                        .IsRequired();

                    b.Navigation("DecisionDrivers");

                    b.Navigation("DecisionText")
                        .IsRequired();

                    b.Navigation("DeprecationReason");

                    b.Navigation("Options");

                    b.Navigation("SupersessionReason");

                    b.Navigation("Title")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
