// <auto-generated />
using System;
using Acmp.Modules.Risks.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acmp.Modules.Risks.Infrastructure.Migrations
{
    [DbContext(typeof(RisksDbContext))]
    partial class RisksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("risks")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acmp.Modules.Risks.Domain.Risk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AcceptingAuthority")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EscalationTarget")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Impact")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Likelihood")
                        .HasColumnType("int");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubjectKey")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("SubjectType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("SubjectType", "SubjectId");

                    b.ToTable("risks", "risks");
                });

            modelBuilder.Entity("Acmp.Modules.Risks.Infrastructure.Persistence.RiskKeyCounter", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Next")
                        .HasColumnType("int");

                    b.HasKey("Prefix", "Year");

                    b.ToTable("risk_key_counters", "risks");
                });

            modelBuilder.Entity("Acmp.Modules.Risks.Domain.Risk", b =>
                {
                    b.OwnsMany("Acmp.Modules.Risks.Domain.Mitigation", "Mitigations", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<DateTimeOffset?>("DueDate")
                                .HasColumnType("datetimeoffset");

                            b1.Property<Guid?>("LinkedActionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("OwnerUserId")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<Guid>("PublicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("RiskEntityId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("PublicId")
                                .IsUnique();

                            b1.HasIndex("RiskEntityId");

                            b1.ToTable("risk_mitigations", "risks");

                            b1.WithOwner()
                                .HasForeignKey("RiskEntityId");

                            b1.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Description", b2 =>
                                {
                                    b2.Property<long>("MitigationId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Ar")
                                        .IsRequired()
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("description_ar");

                                    b2.Property<string>("En")
                                        .IsRequired()
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("description_en");

                                    b2.HasKey("MitigationId");

                                    b2.ToTable("risk_mitigations", "risks");

                                    b2.WithOwner()
                                        .HasForeignKey("MitigationId");
                                });

                            b1.Navigation("Description")
                                .IsRequired();
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "AcceptanceRationale", b1 =>
                        {
                            b1.Property<long>("RiskId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("acceptance_rationale_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("acceptance_rationale_en");

                            b1.HasKey("RiskId");

                            b1.ToTable("risks", "risks");

                            b1.WithOwner()
                                .HasForeignKey("RiskId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "ClosureNote", b1 =>
                        {
                            b1.Property<long>("RiskId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("closure_note_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("closure_note_en");

                            b1.HasKey("RiskId");

                            b1.ToTable("risks", "risks");

                            b1.WithOwner()
                                .HasForeignKey("RiskId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Description", b1 =>
                        {
                            b1.Property<long>("RiskId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("description_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("description_en");

                            b1.HasKey("RiskId");

                            b1.ToTable("risks", "risks");

                            b1.WithOwner()
                                .HasForeignKey("RiskId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "EscalationReason", b1 =>
                        {
                            b1.Property<long>("RiskId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("escalation_reason_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("escalation_reason_en");

                            b1.HasKey("RiskId");

                            b1.ToTable("risks", "risks");

                            b1.WithOwner()
                                .HasForeignKey("RiskId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Title", b1 =>
                        {
                            b1.Property<long>("RiskId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("title_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("title_en");

                            b1.HasKey("RiskId");

                            b1.ToTable("risks", "risks");

                            b1.WithOwner()
                                .HasForeignKey("RiskId");
                        });

                    b.Navigation("AcceptanceRationale");

                    b.Navigation("ClosureNote");

                    b.Navigation("Description");

                    b.Navigation("EscalationReason");

                    b.Navigation("Mitigations");

                    b.Navigation("Title")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
