// <auto-generated />
using System;
using Acmp.Modules.Meetings.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acmp.Modules.Meetings.Infrastructure.Migrations
{
    [DbContext(typeof(MeetingsDbContext))]
    [Migration("20260708160222_Meetings_AddRecordingUpload")]
    partial class Meetings_AddRecordingUpload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("meetings")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acmp.Modules.Meetings.Domain.Agenda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("MeetingId")
                        .IsUnique();

                    b.ToTable("agendas", "meetings");
                });

            modelBuilder.Entity("Acmp.Modules.Meetings.Domain.Meeting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChairName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ChairUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommitteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("HeldAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("JoinUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Location")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecordingContentType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RecordingDownloadUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int?>("RecordingDurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("RecordingFileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RecordingObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("RecordingSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("RecordingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("ScheduledEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ScheduledStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WebexMeetingId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("ScheduledStart");

                    b.HasIndex("Status");

                    b.HasIndex("WebexMeetingId");

                    b.ToTable("meetings", "meetings");
                });

            modelBuilder.Entity("Acmp.Modules.Meetings.Domain.MinutesOfMeeting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ApprovedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("ApprovedBySoleAuthor")
                        .HasColumnType("bit");

                    b.Property<string>("ApprovedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MeetingKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("MeetingTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupersededByMinutesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("minutes_of_meeting", "meetings");
                });

            modelBuilder.Entity("Acmp.Modules.Meetings.Infrastructure.Persistence.MeetingKeyCounter", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Next")
                        .HasColumnType("int");

                    b.HasKey("Prefix", "Year");

                    b.ToTable("meeting_key_counters", "meetings");
                });

            modelBuilder.Entity("Acmp.Modules.Meetings.Domain.Agenda", b =>
                {
                    b.OwnsMany("Acmp.Modules.Meetings.Domain.AgendaItem", "Items", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int>("ActualMinutes")
                                .HasColumnType("int");

                            b1.Property<long>("AgendaEntityId")
                                .HasColumnType("bigint");

                            b1.Property<Guid?>("CarryOverFromAgendaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Order")
                                .HasColumnType("int");

                            b1.Property<int>("Outcome")
                                .HasColumnType("int");

                            b1.Property<string>("PresenterName")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<Guid?>("PresenterUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PublicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("TimeboxMinutes")
                                .HasColumnType("int");

                            b1.Property<Guid>("TopicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("TopicKey")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<string>("TopicTitle")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<bool>("Urgent")
                                .HasColumnType("bit");

                            b1.HasKey("Id");

                            b1.HasIndex("PublicId")
                                .IsUnique();

                            b1.HasIndex("AgendaEntityId", "TopicId")
                                .IsUnique();

                            b1.ToTable("agenda_items", "meetings");

                            b1.WithOwner()
                                .HasForeignKey("AgendaEntityId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Acmp.Modules.Meetings.Domain.Meeting", b =>
                {
                    b.OwnsMany("Acmp.Modules.Meetings.Domain.Attendance", "Attendees", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<bool>("IsVotingEligible")
                                .HasColumnType("bit");

                            b1.Property<DateTimeOffset?>("JoinedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<DateTimeOffset?>("LeftAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<long>("MeetingEntityId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<Guid>("PublicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Role")
                                .HasColumnType("int");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("PublicId")
                                .IsUnique();

                            b1.HasIndex("MeetingEntityId", "UserId")
                                .IsUnique();

                            b1.ToTable("meeting_attendance", "meetings");

                            b1.WithOwner()
                                .HasForeignKey("MeetingEntityId");
                        });

                    b.OwnsMany("Acmp.Modules.Meetings.Domain.Discussion", "Discussions", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("AuthorName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("AuthorSub")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<bool>("IsApproved")
                                .HasColumnType("bit");

                            b1.Property<long>("MeetingEntityId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Origin")
                                .HasColumnType("int");

                            b1.Property<Guid>("PublicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("TopicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("datetimeoffset");

                            b1.HasKey("Id");

                            b1.HasIndex("MeetingEntityId");

                            b1.HasIndex("PublicId")
                                .IsUnique();

                            b1.ToTable("meeting_discussions", "meetings");

                            b1.WithOwner()
                                .HasForeignKey("MeetingEntityId");
                        });

                    b.Navigation("Attendees");

                    b.Navigation("Discussions");
                });

            modelBuilder.Entity("Acmp.Modules.Meetings.Domain.MinutesOfMeeting", b =>
                {
                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Summary", b1 =>
                        {
                            b1.Property<long>("MinutesOfMeetingId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("summary_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("summary_en");

                            b1.HasKey("MinutesOfMeetingId");

                            b1.ToTable("minutes_of_meeting", "meetings");

                            b1.WithOwner()
                                .HasForeignKey("MinutesOfMeetingId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "SupersessionReason", b1 =>
                        {
                            b1.Property<long>("MinutesOfMeetingId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("supersession_reason_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("supersession_reason_en");

                            b1.HasKey("MinutesOfMeetingId");

                            b1.ToTable("minutes_of_meeting", "meetings");

                            b1.WithOwner()
                                .HasForeignKey("MinutesOfMeetingId");
                        });

                    b.Navigation("Summary")
                        .IsRequired();

                    b.Navigation("SupersessionReason");
                });
#pragma warning restore 612, 618
        }
    }
}
