// <auto-generated />
using System;
using Acmp.Modules.Research.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acmp.Modules.Research.Infrastructure.Migrations
{
    [DbContext(typeof(ResearchDbContext))]
    partial class ResearchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("research")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acmp.Modules.Research.Domain.ResearchMission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("KeystonePackageRef")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SourceTopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("research_missions", "research");
                });

            modelBuilder.Entity("Acmp.Modules.Research.Infrastructure.Persistence.ResearchKeyCounter", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Next")
                        .HasColumnType("int");

                    b.HasKey("Prefix", "Year");

                    b.ToTable("research_key_counters", "research");
                });

            modelBuilder.Entity("Acmp.Modules.Research.Domain.ResearchMission", b =>
                {
                    b.OwnsMany("Acmp.Modules.Research.Domain.Finding", "Findings", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int>("Confidence")
                                .HasColumnType("int");

                            b1.Property<bool>("IsVerified")
                                .HasColumnType("bit");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<long>("MissionEntityId")
                                .HasColumnType("bigint");

                            b1.Property<Guid>("PublicId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("MissionEntityId");

                            b1.HasIndex("PublicId")
                                .IsUnique();

                            b1.ToTable("research_findings", "research");

                            b1.WithOwner()
                                .HasForeignKey("MissionEntityId");

                            b1.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Detail", b2 =>
                                {
                                    b2.Property<long>("FindingId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Ar")
                                        .IsRequired()
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("detail_ar");

                                    b2.Property<string>("En")
                                        .IsRequired()
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("detail_en");

                                    b2.HasKey("FindingId");

                                    b2.ToTable("research_findings", "research");

                                    b2.WithOwner()
                                        .HasForeignKey("FindingId");
                                });

                            b1.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Summary", b2 =>
                                {
                                    b2.Property<long>("FindingId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Ar")
                                        .IsRequired()
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("summary_ar");

                                    b2.Property<string>("En")
                                        .IsRequired()
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("summary_en");

                                    b2.HasKey("FindingId");

                                    b2.ToTable("research_findings", "research");

                                    b2.WithOwner()
                                        .HasForeignKey("FindingId");
                                });

                            b1.Navigation("Detail");

                            b1.Navigation("Summary")
                                .IsRequired();
                        });

                    b.OwnsMany("Acmp.Modules.Research.Domain.Recommendation", "Recommendations", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<Guid?>("LinkedTopicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("MissionEntityId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Priority")
                                .HasColumnType("int");

                            b1.Property<Guid>("PublicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("MissionEntityId");

                            b1.HasIndex("PublicId")
                                .IsUnique();

                            b1.ToTable("research_recommendations", "research");

                            b1.WithOwner()
                                .HasForeignKey("MissionEntityId");

                            b1.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Rationale", b2 =>
                                {
                                    b2.Property<long>("RecommendationId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Ar")
                                        .IsRequired()
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("rationale_ar");

                                    b2.Property<string>("En")
                                        .IsRequired()
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("rationale_en");

                                    b2.HasKey("RecommendationId");

                                    b2.ToTable("research_recommendations", "research");

                                    b2.WithOwner()
                                        .HasForeignKey("RecommendationId");
                                });

                            b1.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Statement", b2 =>
                                {
                                    b2.Property<long>("RecommendationId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Ar")
                                        .IsRequired()
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("statement_ar");

                                    b2.Property<string>("En")
                                        .IsRequired()
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("statement_en");

                                    b2.HasKey("RecommendationId");

                                    b2.ToTable("research_recommendations", "research");

                                    b2.WithOwner()
                                        .HasForeignKey("RecommendationId");
                                });

                            b1.Navigation("Rationale");

                            b1.Navigation("Statement")
                                .IsRequired();
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "CancellationReason", b1 =>
                        {
                            b1.Property<long>("ResearchMissionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("cancellation_reason_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("cancellation_reason_en");

                            b1.HasKey("ResearchMissionId");

                            b1.ToTable("research_missions", "research");

                            b1.WithOwner()
                                .HasForeignKey("ResearchMissionId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Question", b1 =>
                        {
                            b1.Property<long>("ResearchMissionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("question_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("question_en");

                            b1.HasKey("ResearchMissionId");

                            b1.ToTable("research_missions", "research");

                            b1.WithOwner()
                                .HasForeignKey("ResearchMissionId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Title", b1 =>
                        {
                            b1.Property<long>("ResearchMissionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("title_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("title_en");

                            b1.HasKey("ResearchMissionId");

                            b1.ToTable("research_missions", "research");

                            b1.WithOwner()
                                .HasForeignKey("ResearchMissionId");
                        });

                    b.Navigation("CancellationReason");

                    b.Navigation("Findings");

                    b.Navigation("Question")
                        .IsRequired();

                    b.Navigation("Recommendations");

                    b.Navigation("Title")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
