// <auto-generated />
using System;
using Acmp.Modules.Decisions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acmp.Modules.Decisions.Infrastructure.Migrations
{
    [DbContext(typeof(DecisionsDbContext))]
    [Migration("20260715231240_Decisions_BallotChain")]
    partial class Decisions_BallotChain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("decisions")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acmp.Modules.Decisions.Domain.Decision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ChairApprovedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ChairApprovedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("ChairOverride")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupersededByDecisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("VoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("TopicId");

                    b.ToTable("decisions", "decisions");
                });

            modelBuilder.Entity("Acmp.Modules.Decisions.Domain.Vote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowAbstain")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ChainSealedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CounterName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CounterUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("OpenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("options_json");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tally")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("tally_json");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("TopicId");

                    b.ToTable("votes", "decisions");
                });

            modelBuilder.Entity("Acmp.Modules.Decisions.Infrastructure.Persistence.DecisionKeyCounter", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Next")
                        .HasColumnType("int");

                    b.HasKey("Prefix", "Year");

                    b.ToTable("decision_key_counters", "decisions");
                });

            modelBuilder.Entity("Acmp.Modules.Decisions.Domain.Decision", b =>
                {
                    b.OwnsMany("Acmp.Modules.Decisions.Domain.DecisionCondition", "Conditions", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<long>("DecisionEntityId")
                                .HasColumnType("bigint");

                            b1.Property<DateTimeOffset?>("DueDate")
                                .HasColumnType("datetimeoffset");

                            b1.Property<Guid?>("LinkedActionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PublicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("DecisionEntityId");

                            b1.HasIndex("PublicId")
                                .IsUnique();

                            b1.ToTable("decision_conditions", "decisions");

                            b1.WithOwner()
                                .HasForeignKey("DecisionEntityId");

                            b1.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Text", b2 =>
                                {
                                    b2.Property<long>("DecisionConditionId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Ar")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("nvarchar(2000)")
                                        .HasColumnName("text_ar");

                                    b2.Property<string>("En")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("nvarchar(2000)")
                                        .HasColumnName("text_en");

                                    b2.HasKey("DecisionConditionId");

                                    b2.ToTable("decision_conditions", "decisions");

                                    b2.WithOwner()
                                        .HasForeignKey("DecisionConditionId");
                                });

                            b1.Navigation("Text")
                                .IsRequired();
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Alternatives", b1 =>
                        {
                            b1.Property<long>("DecisionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("alternatives_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("alternatives_en");

                            b1.HasKey("DecisionId");

                            b1.ToTable("decisions", "decisions");

                            b1.WithOwner()
                                .HasForeignKey("DecisionId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "OverrideJustification", b1 =>
                        {
                            b1.Property<long>("DecisionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("override_justification_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("override_justification_en");

                            b1.HasKey("DecisionId");

                            b1.ToTable("decisions", "decisions");

                            b1.WithOwner()
                                .HasForeignKey("DecisionId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Rationale", b1 =>
                        {
                            b1.Property<long>("DecisionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("rationale_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("rationale_en");

                            b1.HasKey("DecisionId");

                            b1.ToTable("decisions", "decisions");

                            b1.WithOwner()
                                .HasForeignKey("DecisionId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Statement", b1 =>
                        {
                            b1.Property<long>("DecisionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("statement_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("statement_en");

                            b1.HasKey("DecisionId");

                            b1.ToTable("decisions", "decisions");

                            b1.WithOwner()
                                .HasForeignKey("DecisionId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "SupersessionReason", b1 =>
                        {
                            b1.Property<long>("DecisionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("supersession_reason_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("supersession_reason_en");

                            b1.HasKey("DecisionId");

                            b1.ToTable("decisions", "decisions");

                            b1.WithOwner()
                                .HasForeignKey("DecisionId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Title", b1 =>
                        {
                            b1.Property<long>("DecisionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("title_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("title_en");

                            b1.HasKey("DecisionId");

                            b1.ToTable("decisions", "decisions");

                            b1.WithOwner()
                                .HasForeignKey("DecisionId");
                        });

                    b.Navigation("Alternatives");

                    b.Navigation("Conditions");

                    b.Navigation("OverrideJustification");

                    b.Navigation("Rationale")
                        .IsRequired();

                    b.Navigation("Statement")
                        .IsRequired();

                    b.Navigation("SupersessionReason");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Acmp.Modules.Decisions.Domain.Vote", b =>
                {
                    b.OwnsMany("Acmp.Modules.Decisions.Domain.Ballot", "Ballots", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<DateTimeOffset?>("CastAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Choice")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("Hash")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("PreviousHash")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<Guid>("PublicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Recused")
                                .HasColumnType("bit");

                            b1.Property<long>("VoteEntityId")
                                .HasColumnType("bigint");

                            b1.Property<string>("VoterName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("VoterUserId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.HasKey("Id");

                            b1.HasIndex("PublicId")
                                .IsUnique();

                            b1.HasIndex("VoteEntityId", "VoterUserId")
                                .IsUnique();

                            b1.ToTable("vote_ballots", "decisions");

                            b1.WithOwner()
                                .HasForeignKey("VoteEntityId");

                            b1.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Comment", b2 =>
                                {
                                    b2.Property<long>("BallotId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Ar")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("nvarchar(2000)")
                                        .HasColumnName("comment_ar");

                                    b2.Property<string>("En")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("nvarchar(2000)")
                                        .HasColumnName("comment_en");

                                    b2.HasKey("BallotId");

                                    b2.ToTable("vote_ballots", "decisions");

                                    b2.WithOwner()
                                        .HasForeignKey("BallotId");
                                });

                            b1.Navigation("Comment");
                        });

                    b.OwnsOne("Acmp.Modules.Decisions.Domain.QuorumRule", "QuorumRule", b1 =>
                        {
                            b1.Property<long>("VoteId")
                                .HasColumnType("bigint");

                            b1.Property<int>("MinCast")
                                .HasColumnType("int")
                                .HasColumnName("quorum_min_cast");

                            b1.Property<int>("MinPresent")
                                .HasColumnType("int")
                                .HasColumnName("quorum_min_present");

                            b1.HasKey("VoteId");

                            b1.ToTable("votes", "decisions");

                            b1.WithOwner()
                                .HasForeignKey("VoteId");
                        });

                    b.Navigation("Ballots");

                    b.Navigation("QuorumRule")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
