// <auto-generated />
using System;
using Acmp.Modules.Knowledge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acmp.Modules.Knowledge.Infrastructure.Migrations
{
    [DbContext(typeof(KnowledgeDbContext))]
    [Migration("20260715022510_Knowledge_AddSearchIndex")]
    partial class Knowledge_AddSearchIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("knowledge")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acmp.Modules.Knowledge.Domain.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("_tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("documents", "knowledge");
                });

            modelBuilder.Entity("Acmp.Modules.Knowledge.Domain.Template", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TargetType");

                    b.ToTable("templates", "knowledge");
                });

            modelBuilder.Entity("Acmp.Modules.Knowledge.Infrastructure.Persistence.KnowledgeKeyCounter", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Next")
                        .HasColumnType("int");

                    b.HasKey("Prefix", "Year");

                    b.ToTable("knowledge_key_counters", "knowledge");
                });

            modelBuilder.Entity("Acmp.Modules.Knowledge.Domain.Document", b =>
                {
                    b.OwnsMany("Acmp.Modules.Knowledge.Domain.DocumentVersion", "Versions", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<long>("DocumentEntityId")
                                .HasColumnType("bigint");

                            b1.Property<Guid>("PublicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("SavedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("SavedByUserId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<int>("Version")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("DocumentEntityId");

                            b1.HasIndex("PublicId")
                                .IsUnique();

                            b1.ToTable("knowledge_document_versions", "knowledge");

                            b1.WithOwner()
                                .HasForeignKey("DocumentEntityId");

                            b1.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Body", b2 =>
                                {
                                    b2.Property<long>("DocumentVersionId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Ar")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("body_ar");

                                    b2.Property<string>("En")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("body_en");

                                    b2.HasKey("DocumentVersionId");

                                    b2.ToTable("knowledge_document_versions", "knowledge");

                                    b2.WithOwner()
                                        .HasForeignKey("DocumentVersionId");
                                });

                            b1.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Title", b2 =>
                                {
                                    b2.Property<long>("DocumentVersionId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Ar")
                                        .IsRequired()
                                        .HasMaxLength(512)
                                        .HasColumnType("nvarchar(512)")
                                        .HasColumnName("title_ar");

                                    b2.Property<string>("En")
                                        .IsRequired()
                                        .HasMaxLength(512)
                                        .HasColumnType("nvarchar(512)")
                                        .HasColumnName("title_en");

                                    b2.HasKey("DocumentVersionId");

                                    b2.ToTable("knowledge_document_versions", "knowledge");

                                    b2.WithOwner()
                                        .HasForeignKey("DocumentVersionId");
                                });

                            b1.Navigation("Body")
                                .IsRequired();

                            b1.Navigation("Title")
                                .IsRequired();
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Body", b1 =>
                        {
                            b1.Property<long>("DocumentId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("body_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("body_en");

                            b1.HasKey("DocumentId");

                            b1.ToTable("documents", "knowledge");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId");
                        });

                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Title", b1 =>
                        {
                            b1.Property<long>("DocumentId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("title_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("title_en");

                            b1.HasKey("DocumentId");

                            b1.ToTable("documents", "knowledge");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId");
                        });

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Acmp.Modules.Knowledge.Domain.Template", b =>
                {
                    b.OwnsOne("Acmp.Shared.Domain.ValueObjects.LocalizedString", "Name", b1 =>
                        {
                            b1.Property<long>("TemplateId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("name_en");

                            b1.HasKey("TemplateId");

                            b1.ToTable("templates", "knowledge");

                            b1.WithOwner()
                                .HasForeignKey("TemplateId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
