// <auto-generated />
using System;
using Acmp.Modules.Topics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acmp.Modules.Topics.Infrastructure.Migrations
{
    [DbContext(typeof(TopicsDbContext))]
    [Migration("20260713134750_Topics_ConvertProvenance")]
    partial class Topics_ConvertProvenance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("topics")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acmp.Modules.Topics.Domain.Topic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevisitOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<Guid?>("SourceRecommendationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SubmittedBySub")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("TimesDeferred")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Urgency")
                        .HasColumnType("int");

                    b.Property<string>("_streams")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("streams");

                    b.Property<string>("_systems")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("systems");

                    b.Property<string>("_tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("SourceRecommendationId")
                        .IsUnique()
                        .HasFilter("[SourceRecommendationId] IS NOT NULL");

                    b.HasIndex("Status");

                    b.ToTable("topics", "topics");
                });

            modelBuilder.Entity("Acmp.Modules.Topics.Infrastructure.Persistence.TopicKeyCounter", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Next")
                        .HasColumnType("int");

                    b.HasKey("Year");

                    b.ToTable("topic_key_counters", "topics");
                });

            modelBuilder.Entity("Acmp.Modules.Topics.Domain.Topic", b =>
                {
                    b.OwnsMany("Acmp.Modules.Topics.Domain.TopicAttachment", "Attachments", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<Guid>("PublicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<long>("TopicEntityId")
                                .HasColumnType("bigint");

                            b1.Property<DateTimeOffset>("UploadedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("UploadedByName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("UploadedBySub")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.HasKey("Id");

                            b1.HasIndex("PublicId")
                                .IsUnique();

                            b1.HasIndex("TopicEntityId");

                            b1.ToTable("topic_attachments", "topics");

                            b1.WithOwner()
                                .HasForeignKey("TopicEntityId");
                        });

                    b.OwnsMany("Acmp.Modules.Topics.Domain.TopicComment", "Comments", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("AuthorName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("AuthorSub")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTimeOffset>("PostedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<Guid>("PublicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("TopicEntityId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("PublicId")
                                .IsUnique();

                            b1.HasIndex("TopicEntityId");

                            b1.ToTable("topic_comments", "topics");

                            b1.WithOwner()
                                .HasForeignKey("TopicEntityId");
                        });

                    b.OwnsMany("Acmp.Modules.Topics.Domain.TopicStatusEvent", "History", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("ActorName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("ActorSub")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<int>("FromStatus")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<Guid>("PublicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Reason")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<int>("ToStatus")
                                .HasColumnType("int");

                            b1.Property<long>("TopicEntityId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("PublicId")
                                .IsUnique();

                            b1.HasIndex("TopicEntityId");

                            b1.ToTable("topic_status_events", "topics");

                            b1.WithOwner()
                                .HasForeignKey("TopicEntityId");
                        });

                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
